package view;

import service.KeuanganManager;
import model.Transaksi;
import javax.swing.*;
import java.time.LocalDate;
import java.time.format.DateTimeParseException;
import java.io.File;
import java.awt.event.ActionEvent;
import java.awt.event.MouseEvent;
import java.awt.Component;
import java.util.List;


/**
 *
 * @author User
 */
public class AplikasiKeuanganGUI extends javax.swing.JFrame {

     // PROPERTI APLIKASI
    private KeuanganManager manager = new KeuanganManager();
    private DefaultListModel<Transaksi> listModel = new DefaultListModel<>();
    
    /**
     * Creates new form AplikasiKeuanganGUI
     */
    public AplikasiKeuanganGUI() {
        initComponents();
        
        // Setup ComboBox
        cmbJenis.addItem("Pemasukan");
        cmbJenis.addItem("Pengeluaran");
        
        // Set tanggal default
        txtTanggal.setText(LocalDate.now().toString());
        
        // Setup JList dengan model yang benar
        jListTransaksi.setModel(listModel);
        
        // Setup custom renderer untuk JList
        jListTransaksi.setCellRenderer(new DefaultListCellRenderer() {
            @Override
            public Component getListCellRendererComponent(JList list, Object value, int index, 
                                                         boolean isSelected, boolean cellHasFocus) {
                Component c = super.getListCellRendererComponent(list, value, index, isSelected, cellHasFocus);
                if (value instanceof Transaksi) {
                    Transaksi t = (Transaksi) value;
                    setText(t.toString());
                }
                return c;
            }
        });
        
        // Contoh data awal
        manager.tambahTransaksi(new Transaksi(LocalDate.now(), "Gaji Utama", 5000000.0, "Pemasukan"));
        manager.tambahTransaksi(new Transaksi(LocalDate.now().minusDays(3), "Bayar Kost", 1000000.0, "Pengeluaran"));
        
        updateTampilan();
    }
    
    /**
     * Memperbarui tampilan JList dan Label Saldo.
     */
    private void updateTampilan() {
        listModel.clear(); // Kosongkan model terlebih dahulu
        
        List<Transaksi> semuaTransaksi = manager.getAllTransaksi();
        for (Transaksi t : semuaTransaksi) {
            listModel.addElement(t);
        }
        
        // Update label saldo
        lblSaldo.setText("SALDO SAAT INI: Rp " + String.format("%,.2f", manager.hitungSaldo()));
    }
    
    /**
     * Mengosongkan input fields setelah operasi.
     */
    private void clearInputFields() {
        txtTanggal.setText(LocalDate.now().toString()); 
        txtDeskripsi.setText("");
        txtJumlah.setText("");
        cmbJenis.setSelectedIndex(0);
        jListTransaksi.clearSelection();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTanggal = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabelDeskripsi = new javax.swing.JLabel();
        txtDeskripsi = new javax.swing.JTextField();
        jLabelJumlah = new javax.swing.JLabel();
        jLabelJenis = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        cmbJenis = new javax.swing.JComboBox<>();
        btnTambah = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnImpor = new javax.swing.JButton();
        btnEkspor = new javax.swing.JButton();
        lblSaldo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListTransaksi = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTanggal.setText("Tanggal (yyyy-MM-dd)");

        jLabelDeskripsi.setText("Deskripsi/Keterangan");

        jLabelJumlah.setText("Jumlah (Rp)");

        jLabelJenis.setText("Jenis Transaksi");

        btnTambah.setText("Tambah");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnImpor.setText(" Impor JSON");
        btnImpor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImporActionPerformed(evt);
            }
        });

        btnEkspor.setText("Ekspor JSON");
        btnEkspor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEksporActionPerformed(evt);
            }
        });

        lblSaldo.setText("Saldo Saat Ini: Rp 0.00");

        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 150));

        jListTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jListTransaksi);

        jLabel1.setText("APLIKASI KEUANGAN PRIBADI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelJenis)
                                    .addComponent(jLabelJumlah)
                                    .addComponent(jLabelDeskripsi)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                            .addGap(124, 124, 124)
                                            .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(149, 149, 149)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(cmbJenis, 0, 107, Short.MAX_VALUE)
                                                .addComponent(txtJumlah)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnUbah, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTanggal)
                                .addGap(26, 26, 26)
                                .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEkspor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImpor))
                            .addComponent(lblSaldo)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(140, 140, 140))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTanggal)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelDeskripsi)
                    .addComponent(txtDeskripsi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTambah))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJenis)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUbah))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(lblSaldo)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEkspor)
                    .addComponent(btnImpor))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
       int selectedIndex = jListTransaksi.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Pilih entri yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Transaksi selected = listModel.getElementAt(selectedIndex);
        
        int confirm = JOptionPane.showConfirmDialog(this, 
                "Yakin hapus transaksi: " + selected.getDeskripsi() + "?", 
                "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            manager.hapusTransaksi(selected);
            updateTampilan();
            clearInputFields();
        }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        // TODO add your handling code here:
     int selectedIndex = jListTransaksi.getSelectedIndex();
        if (selectedIndex == -1) {
            JOptionPane.showMessageDialog(this, "Pilih entri yang ingin diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Transaksi selectedLama = listModel.getElementAt(selectedIndex);
        
        try {
            Transaksi transaksiBaru = new Transaksi(
                LocalDate.parse(txtTanggal.getText()),
                txtDeskripsi.getText(),
                Double.parseDouble(txtJumlah.getText().replace(",", "")),
                (String) cmbJenis.getSelectedItem()
            );
            
            manager.ubahTransaksi(selectedLama, transaksiBaru);
            updateTampilan();
            clearInputFields();
            JOptionPane.showMessageDialog(this, "Transaksi berhasil diubah.");
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Data input tidak valid. Pastikan format benar.", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
         try {
            String deskripsi = txtDeskripsi.getText();
            double jumlah = Double.parseDouble(txtJumlah.getText().replace(",", "")); 
            LocalDate tanggal = LocalDate.parse(txtTanggal.getText()); 
            String jenis = (String) cmbJenis.getSelectedItem();

            if (deskripsi.isEmpty() || jumlah <= 0) {
                 JOptionPane.showMessageDialog(this, "Deskripsi dan Jumlah wajib diisi dengan benar.", "Error", JOptionPane.ERROR_MESSAGE);
                 return;
            }
            Transaksi transaksiBaru = new Transaksi(tanggal, deskripsi, jumlah, jenis);
            manager.tambahTransaksi(transaksiBaru);
            updateTampilan();
            clearInputFields();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Jumlah harus berupa angka yang valid.", "Input Error", JOptionPane.ERROR_MESSAGE);
        } catch (DateTimeParseException e) {
             JOptionPane.showMessageDialog(this, "Format Tanggal tidak valid (Gunakan yyyy-MM-dd).", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnImporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImporActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Pilih File JSON untuk Diimpor");

        if (fileChooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (manager.importDataFromJson(path)) {
                updateTampilan();
                JOptionPane.showMessageDialog(this, "Data berhasil diimpor.");
            } else {
                 JOptionPane.showMessageDialog(this, "Impor Gagal! Pastikan file JSON valid.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnImporActionPerformed

    private void btnEksporActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEksporActionPerformed
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Simpan Transaksi sebagai JSON");
        fileChooser.setSelectedFile(new File("KeuanganPribadi_Export.json"));

        if (fileChooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            String path = fileChooser.getSelectedFile().getAbsolutePath();
            if (manager.exportDataToJson(path)) {
                JOptionPane.showMessageDialog(this, "Data berhasil diekspor ke: " + path);
            } else {
                 JOptionPane.showMessageDialog(this, "Ekspor Gagal!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnEksporActionPerformed

    private void jListTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListTransaksiMouseClicked
        // TODO add your handling code here:
         if (evt.getClickCount() == 1) { // Single click
            int index = jListTransaksi.getSelectedIndex();
            if (index >= 0) {
                Transaksi selected = listModel.getElementAt(index);
                // Isi field dengan data transaksi yang dipilih
                txtTanggal.setText(selected.getTanggal().toString());
                txtDeskripsi.setText(selected.getDeskripsi());
                txtJumlah.setText(String.valueOf(selected.getJumlah()));
                cmbJenis.setSelectedItem(selected.getJenis());
            }
        }
    }//GEN-LAST:event_jListTransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKeuanganGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKeuanganGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkspor;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnImpor;
    private javax.swing.JButton btnTambah;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDeskripsi;
    private javax.swing.JLabel jLabelJenis;
    private javax.swing.JLabel jLabelJumlah;
    private javax.swing.JLabel jLabelTanggal;
    private javax.swing.JList jListTransaksi;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JTextField txtDeskripsi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables

}
